accueil:
    path: /{_locale}
    controller: App\Controller\AccueilController::pageAccueil
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

fuert:
    path: /{_locale}/fuerteventura
    controller: App\Controller\AccueilController::fuerteventura
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

concept:
    path: /{_locale}/concept-contact
    controller: App\Controller\AccueilController::concept_contact
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

contact:
    path: /{_locale}/contact
    controller: App\Controller\AccueilController::contact
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

reserver:
    path: /{_locale}/reserver
    controller: App\Controller\AccueilController::reserver
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr